version: "3.7"

services:
  app:
    build: .
    command: npm run dev
    restart: unless-stopped
    ports:
      - "${APP_HOST_PORT}:${APP_CONT_PORT}"
    depends_on:
      - db
      - swagger-editor
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine
    restart: unless-stopped
    ports:
      - "${DB_HOST_PORT}:${DB_CONT_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - creamcats-db:/var/lib/postgresql/data

  swagger-editor:
    image: "swaggerapi/swagger-editor"
    restart: unless-stopped
    ports:
      - "${SWAGGER_EDITOR_HOST_PORT}:${SWAGGER_EDITOR_CONT_PORT}"

volumes:
  creamcats-db: {}
