version: "3.7"

services:
  app:
    container_name: "${APP_CONT_NAME}"
    build: .
    command: npm run dev
    restart: unless-stopped
    ports:
      - "${APP_HOST_PORT}:${APP_CONT_PORT}"
      - "${PRISMA_STUDIO_HOST_PORT}:${PRISMA_STUDIO_CONT_PORT}"
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env
      - ./api-doc:/app/api-doc
      - ./prisma:/app/prisma
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json

  db:
    container_name: "${DB_CONT_NAME}"
    image: postgis/postgis:latest
    restart: unless-stopped
    ports:
      - "${DB_HOST_PORT}:${DB_CONT_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - creamcats-db:/var/lib/postgresql/data
      - ./sql:/sql

volumes:
  creamcats-db: {}
